mklink /J junctions\adummy ..\adummy-targetdirs\adummy
mklink /J junctions\adummy2 ..\adummy-targetdirs\adummy2
mklink /J junctions\a-dummy ..\adummy-targetdirs\a-dummy
mklink /J junctions\a-dummy2 ..\adummy-targetdirs\a-dummy2
mklink /J junctions\a-dummy3 ..\adummy-targetdirs\a-dummy3
mklink /J junctions\aZZZdummy ..\adummy-targetdirs\aZZZdummy
mklink /J junctions\aZZZdummy2 ..\adummy-targetdirs\aZZZdummy2
mklink /J junctions\xdummy ..\adummy-targetdirs\xdummy
mklink /J junctions\xdummyA ..\adummy-targetdirs\xdummyA
mklink /J junctions\z ..\adummy-targetdirs\z
mklink /J junctions\zdummyA ..\adummy-targetdirs\zdummyA
mklink /J junctions\zdummyB ..\adummy-targetdirs\zdummyB
